"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#qf+!01c&eet&=v&ksnj4^d5v1jiu#qdzntt(a=7-sfhx_%iy7"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # 允许所有主机访问（开发环境）


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders", # 新增: 处理前端跨域
    "rest_framework", # 新增: DRF
    "analyzer", # 新增: 我们的业务 App
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", # 新增: 跨域中间件 (必须放在最前)
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'code_diff_project',
#         'USER': 'root',
#         'PASSWORD': '123456',
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {
#             'charset': 'utf8mb4',
#         }
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'code_diff_project',
        'USER': 'root',
        'PASSWORD': 'Aa123456@',
        'HOST': '172.16.190.194',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# CORS Config
CORS_ALLOW_ALL_ORIGINS = True # 开发环境允许所有跨域

# Git 访问 Token 配置
# 为特定 Git 服务器配置内置 Token，避免每次都需要输入密码
GIT_TOKENS = {
    'git.hrlyit.com': 'Cs8ySNvnohGLBxC4esgy',  # hrlyit Git 服务器的访问 Token
}

# DeepSeek AI API 配置
# 用于代码分析的 AI 服务
DEEPSEEK_API_KEY = "sk-z530Iu4wiKKJqaw2TU7OeVqPj0j9d0tavygB8izRFfTMA7NY"
# DEEPSEEK_API_URL = "https://api.chataiapi.com/v1/chat/completions"
DEEPSEEK_API_URL = "https://api.vectorengine.ai/v1/chat/completions"  # 修正：添加完整路径
DEEPSEEK_MODEL = "gemini-2.5-flash"

# 初始化日志配置
# 在 Django 启动时自动配置 loguru 日志系统
try:
    from analyzer.log_config import setup_logger
    # 日志配置会在 log_config 模块导入时自动初始化
except Exception as e:
    print(f"警告：日志配置初始化失败: {e}")
