# Generated by Django 4.2.27 on 2025-12-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('change_intent', models.TextField(blank=True, null=True, verbose_name='变更意图')),
                ('risk_level', models.CharField(max_length=50, verbose_name='风险等级')),
                ('report_json', models.JSONField(verbose_name='完整报告JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
            ],
            options={
                'verbose_name': '分析报告',
                'verbose_name_plural': '分析报告',
                'db_table': 'analysis_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
