# Generated by Django 4.2.27 on 2025-12-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0003_analysisreport_project_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=255, verbose_name="项目名称"),
                ),
                (
                    "mode",
                    models.CharField(
                        default="local", max_length=20, verbose_name="模式"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待中"),
                            ("PROCESSING", "进行中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失败"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "log_details",
                    models.TextField(blank=True, null=True, verbose_name="执行日志"),
                ),
            ],
            options={
                "verbose_name": "分析任务",
                "verbose_name_plural": "分析任务",
                "db_table": "analysis_task",
                "ordering": ["-created_at"],
            },
        ),
    ]
