# Generated by Django 4.2.27 on 2025-12-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="diff_content",
            field=models.TextField(blank=True, null=True, verbose_name="代码Diff"),
        ),
    ]
