# Generated by Django 3.2.23 on 2025-12-08 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_analysistask'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyzer.analysistask', verbose_name='关联任务'),
        ),
    ]
