# Generated by Django 3.2.23 on 2025-12-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_analysisreport_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistask',
            name='source_branch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='工作分支'),
        ),
        migrations.AddField(
            model_name='analysistask',
            name='target_branch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='基准分支'),
        ),
    ]
