# Generated by Django 4.2.27 on 2025-12-19 22:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=255, verbose_name="项目名称"),
                ),
                (
                    "mode",
                    models.CharField(
                        default="local", max_length=20, verbose_name="模式"
                    ),
                ),
                (
                    "source_branch",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="工作分支"
                    ),
                ),
                (
                    "target_branch",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="基准分支"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "等待中"),
                            ("PROCESSING", "进行中"),
                            ("COMPLETED", "已完成"),
                            ("FAILED", "失败"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "log_details",
                    models.TextField(blank=True, null=True, verbose_name="执行日志"),
                ),
            ],
            options={
                "verbose_name": "分析任务",
                "verbose_name_plural": "分析任务",
                "db_table": "analysis_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_project_name",
                    models.CharField(max_length=255, verbose_name="主项目名称"),
                ),
                (
                    "main_project_git_url",
                    models.CharField(max_length=255, verbose_name="主项目Git地址"),
                ),
                (
                    "related_project_name",
                    models.CharField(max_length=255, verbose_name="关联项目名称"),
                ),
                (
                    "related_project_git_url",
                    models.CharField(max_length=255, verbose_name="关联项目Git地址"),
                ),
                (
                    "related_project_branch",
                    models.CharField(
                        default="master", max_length=100, verbose_name="关联项目分支"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "项目关联关系",
                "verbose_name_plural": "项目关联关系",
                "db_table": "project_relation",
                "ordering": ["-created_at"],
                "unique_together": {
                    ("main_project_git_url", "related_project_git_url")
                },
            },
        ),
        migrations.CreateModel(
            name="AnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        default="Unknown Project",
                        max_length=255,
                        verbose_name="项目名称",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "change_intent",
                    models.TextField(blank=True, null=True, verbose_name="变更意图"),
                ),
                (
                    "risk_level",
                    models.CharField(max_length=50, verbose_name="风险等级"),
                ),
                ("report_json", models.JSONField(verbose_name="完整报告JSON")),
                (
                    "diff_content",
                    models.TextField(blank=True, null=True, verbose_name="代码Diff"),
                ),
                (
                    "source_project",
                    models.CharField(
                        default="main",
                        help_text="来源项目名称（main 或关联项目名称）",
                        max_length=255,
                        verbose_name="来源项目",
                    ),
                ),
                (
                    "prompt_tokens",
                    models.IntegerField(default=0, verbose_name="输入Token"),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(default=0, verbose_name="输出Token"),
                ),
                (
                    "total_tokens",
                    models.IntegerField(default=0, verbose_name="总Token"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="分析时间"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analyzer.analysistask",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "分析报告",
                "verbose_name_plural": "分析报告",
                "db_table": "analysis_report",
                "ordering": ["-created_at"],
            },
        ),
    ]
