# Generated by Django 3.2.23 on 2025-12-20 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='组织名称')),
                ('git_server_url', models.CharField(max_length=500, verbose_name='Git服务器地址')),
                ('git_server_type', models.CharField(choices=[('gitlab', 'GitLab'), ('github', 'GitHub'), ('gitea', 'Gitea')], default='gitlab', max_length=50, verbose_name='Git服务器类型')),
                ('access_token', models.CharField(max_length=500, verbose_name='访问Token')),
                ('default_branch', models.CharField(default='master', max_length=100, verbose_name='默认分支')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_discovery_at', models.DateTimeField(blank=True, null=True, verbose_name='上次发现时间')),
                ('discovered_project_count', models.IntegerField(default=0, verbose_name='发现的项目数量')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Git组织配置',
                'verbose_name_plural': 'Git组织配置',
                'db_table': 'git_organization',
                'ordering': ['-created_at'],
                'unique_together': {('git_server_url', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DiscoveredProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('project_path', models.CharField(max_length=500, verbose_name='项目路径')),
                ('git_url', models.CharField(max_length=500, verbose_name='Git地址')),
                ('default_branch', models.CharField(default='master', max_length=100, verbose_name='默认分支')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('language', models.CharField(blank=True, max_length=100, null=True, verbose_name='主要编程语言')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='上次分析时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.gitorganization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '发现的项目',
                'verbose_name_plural': '发现的项目',
                'db_table': 'discovered_project',
                'ordering': ['project_name'],
                'unique_together': {('organization', 'project_path')},
            },
        ),
    ]
