# Generated by Django 3.2.23 on 2025-12-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_analysisreport_diff_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='project_name',
            field=models.CharField(default='Unknown Project', max_length=255, verbose_name='项目名称'),
        ),
    ]
