# Generated by Django 4.2.27 on 2025-12-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0006_auto_20251210_2215"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="completion_tokens",
            field=models.IntegerField(default=0, verbose_name="输出Token"),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="prompt_tokens",
            field=models.IntegerField(default=0, verbose_name="输入Token"),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="total_tokens",
            field=models.IntegerField(default=0, verbose_name="总Token"),
        ),
    ]
