# Generated by Django 3.2.23 on 2025-12-14 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_analysisreport_completion_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='分析时间'),
        ),
        migrations.AlterField(
            model_name='analysistask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
