# Generated by Django 4.1.13 on 2025-12-18 19:32

from django.db import migrations, models, connection
import django.utils.timezone


def add_source_project_if_not_exists(apps, schema_editor):
    """Add source_project column if it doesn't exist"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'analysis_report'
            AND COLUMN_NAME = 'source_project'
        """)
        exists = cursor.fetchone()[0]
        
        if not exists:
            cursor.execute("""
                ALTER TABLE analysis_report
                ADD COLUMN source_project VARCHAR(255) DEFAULT 'main'
                COMMENT '来源项目名称（main 或关联项目名称）'
            """)


def create_project_relation_if_not_exists(apps, schema_editor):
    """Create project_relation table if it doesn't exist"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*)
            FROM information_schema.TABLES
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'project_relation'
        """)
        exists = cursor.fetchone()[0]
        
        if not exists:
            cursor.execute("""
                CREATE TABLE `project_relation` (
                  `id` bigint NOT NULL AUTO_INCREMENT,
                  `main_project_name` varchar(255) NOT NULL COMMENT '主项目名称',
                  `main_project_git_url` varchar(255) NOT NULL COMMENT '主项目Git地址',
                  `related_project_name` varchar(255) NOT NULL COMMENT '关联项目名称',
                  `related_project_git_url` varchar(255) NOT NULL COMMENT '关联项目Git地址',
                  `related_project_branch` varchar(100) NOT NULL DEFAULT 'master' COMMENT '关联项目分支',
                  `is_active` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
                  `created_at` datetime(6) NOT NULL COMMENT '创建时间',
                  `updated_at` datetime(6) NOT NULL COMMENT '更新时间',
                  PRIMARY KEY (`id`),
                  UNIQUE KEY `analyzer_projectrelation_main_project_git_url_re_e8e0e0e5_uniq` (`main_project_git_url`,`related_project_git_url`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目关联关系表'
            """)


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0008_auto_20251214_1641"),
    ]

    operations = [
        migrations.RunPython(add_source_project_if_not_exists, migrations.RunPython.noop),
        migrations.RunPython(create_project_relation_if_not_exists, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ProjectRelation",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "main_project_name",
                            models.CharField(max_length=255, verbose_name="主项目名称"),
                        ),
                        (
                            "main_project_git_url",
                            models.CharField(max_length=255, verbose_name="主项目Git地址"),
                        ),
                        (
                            "related_project_name",
                            models.CharField(max_length=255, verbose_name="关联项目名称"),
                        ),
                        (
                            "related_project_git_url",
                            models.CharField(max_length=255, verbose_name="关联项目Git地址"),
                        ),
                        (
                            "related_project_branch",
                            models.CharField(
                                default="master", max_length=100, verbose_name="关联项目分支"
                            ),
                        ),
                        (
                            "is_active",
                            models.BooleanField(default=True, verbose_name="是否启用"),
                        ),
                        (
                            "created_at",
                            models.DateTimeField(
                                default=django.utils.timezone.now, verbose_name="创建时间"
                            ),
                        ),
                        (
                            "updated_at",
                            models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                        ),
                    ],
                    options={
                        "verbose_name": "项目关联关系",
                        "verbose_name_plural": "项目关联关系",
                        "db_table": "project_relation",
                        "ordering": ["-created_at"],
                        "unique_together": {
                            ("main_project_git_url", "related_project_git_url")
                        },
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
