# Generated by Django 4.2.27 on 2025-12-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0002_discoveredproject_gitorganization"),
        ("analyzer", "0009_analysisreport_source_project_projectrelation"),
    ]

    operations = []
