# Generated by Django 4.1.13 on 2026-01-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0010_merge_20251222_1115"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="api_cost",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="根据输入输出token计算的API调用费用",
                max_digits=10,
                verbose_name="API费用(元)",
            ),
        ),
    ]
