# Generated by Django 4.1.13 on 2026-01-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer", "0011_analysisreport_api_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="input_cost",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="输入token的费用",
                max_digits=10,
                verbose_name="输入费用(元)",
            ),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="output_cost",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="输出token的费用",
                max_digits=10,
                verbose_name="输出费用(元)",
            ),
        ),
        migrations.AlterField(
            model_name="analysisreport",
            name="api_cost",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="输入+输出的总费用",
                max_digits=10,
                verbose_name="API总费用(元)",
            ),
        ),
    ]
