# Generated by Django 4.2.27 on 2026-01-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analyzer",
            "0012_analysisreport_input_cost_analysisreport_output_cost_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analysistask",
            name="base_commit_author",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="基准提交作者"
            ),
        ),
        migrations.AddField(
            model_name="analysistask",
            name="base_commit_date",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="基准提交时间"
            ),
        ),
        migrations.AddField(
            model_name="analysistask",
            name="base_commit_message",
            field=models.TextField(blank=True, null=True, verbose_name="基准提交消息"),
        ),
        migrations.AddField(
            model_name="analysistask",
            name="target_commit_author",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="目标提交作者"
            ),
        ),
        migrations.AddField(
            model_name="analysistask",
            name="target_commit_date",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="目标提交时间"
            ),
        ),
        migrations.AddField(
            model_name="analysistask",
            name="target_commit_message",
            field=models.TextField(blank=True, null=True, verbose_name="目标提交消息"),
        ),
    ]
